[package]
org = "ballerinax"
name = "persist.inmemory"
version = "1.4.1"
authors = ["Ballerina"]
keywords = ["persist", "inmemory"]
repository = "https://github.com/ballerina-platform/module-ballerinax-persist.inmemory"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241011-161100-51978649"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.4.1"
path = "../native/build/libs/persist.inmemory-native-1.4.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "1.4.1"
path = "./lib/persist-native-1.4.1-20241001-120600-2395f0f.jar"
